import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {validate} from '../lib/schema.js';
import {makeExcel,makePDF} from '../lib/exports.js';
import ExcelJS from 'exceljs';
import handler from '../api/index.js';
const applicant={name:'Test Applicant',registrationId:'24-001',university:'Air University',department:'Engineering',program:'BE',studyLevel:'Undergraduate',semester:'3',section:'A',phone:'03001234567',email:'test@example.com',team:'Media & Design',secondTeam:'Technical',role:'Member',skills:'Design and photography',tools:'Canva',portfolio:'',hours:'4–6 hours',motivation:'Contribute to the community.',experience:'',outside:'Yes',outsideDetails:'Applied to an external youth society; awaiting response.',leadership:'',conflict:'',consent:true};
async function call(path,method='GET',body,cookie=''){let result;const req={url:path,method,body,headers:{host:'localhost',origin:'http://localhost','content-type':'application/json',cookie,'x-forwarded-for':'127.0.0.42'}};const headers={};const res={statusCode:200,setHeader(k,v){headers[k]=v;},end(value){result=value;}};await handler(req,res);return {status:res.statusCode,headers,body:result,json:()=>JSON.parse(result)};}
test('conditional questions, roles and team preferences validated on server',()=>{assert.equal(validate(applicant).outsideDetails,applicant.outsideDetails);assert.throws(()=>validate({...applicant,outsideDetails:''}),/outside society/);assert.throws(()=>validate({...applicant,role:'Deputy'}),/leadership questions/);assert.throws(()=>validate({...applicant,secondTeam:applicant.team}),/different second/);assert.throws(()=>validate({...applicant,team:'General Member',role:'Co-Lead'}),/must select Member/);assert.throws(()=>validate({...applicant,consent:false}),/consent/);assert.equal(validate({...applicant,outside:'No'}).outsideDetails,'');});
test('Excel preserves fields and user text as strings; PDF is real PDF',async()=>{const data={...applicant,id:'sample-id',submittedAt:'2026-09-17T00:00:00Z',name:'=SUM(1,2)'};const bytes=await makeExcel([data]);const book=new ExcelJS.Workbook();await book.xlsx.load(bytes);const sheet=book.getWorksheet('Applications');assert.equal(sheet.getCell('C2').value,'=SUM(1,2)');assert.equal(sheet.rowCount,2);assert.ok(sheet.getRow(1).values.includes('Outside society and application outcome'));const pdf=await makePDF([data]);assert.equal(pdf.subarray(0,5).toString(),'%PDF-');assert.ok(pdf.length>1000);});
test('application persistence, duplicate prevention, protected exports and logout',async()=>{const dir=await mkdtemp(join(tmpdir(),'ypdc-test-'));process.env.LOCAL_DATA_DIR=dir;process.env.ADMIN_PASSWORD='test-password-for-suite';process.env.SESSION_SECRET='s'.repeat(64);try{let r=await call('/api/admin/export?format=xlsx');assert.equal(r.status,401);r=await call('/api/applications','POST',applicant);assert.equal(r.status,201);assert.ok(r.json().id);assert.equal((await call('/api/applications','POST',applicant)).status,409);assert.equal((await call('/api/admin/login','POST',{password:'wrong'})).status,401);r=await call('/api/admin/login','POST',{password:process.env.ADMIN_PASSWORD});assert.equal(r.status,200);const cookie=r.headers['Set-Cookie'].split(';')[0];assert.match(r.headers['Set-Cookie'],/HttpOnly/);assert.equal((await call('/api/admin/session','GET',undefined,cookie)).json().count,1);r=await call('/api/admin/export?format=xlsx','GET',undefined,cookie);assert.equal(r.status,200);assert.ok(Buffer.isBuffer(r.body));r=await call('/api/admin/export?format=pdf','GET',undefined,cookie);assert.equal(r.body.subarray(0,5).toString(),'%PDF-');assert.equal((await call('/api/admin/export?format=xlsx','GET',undefined,cookie+'x')).status,401);r=await call('/api/admin/logout','POST',{},cookie);assert.match(r.headers['Set-Cookie'],/Max-Age=0/);assert.equal((await call('/api/admin/session')).status,401);}finally{await rm(dir,{recursive:true,force:true});delete process.env.LOCAL_DATA_DIR;}});
